def exams_data_populate():
    return [
        ("Hemograma Completo", "Contagem de células sanguíneas e plaquetas"),
        ("Glicemia em Jejum", "Medição dos níveis de glicose em jejum"),
        ("Colesterol Total", "Avaliação dos níveis totais de colesterol"),
        ("Raio-X de Tórax", "Imagem radiográfica da região torácica"),
        ("Eletrocardiograma (ECG)", "Registro da atividade elétrica do coração"),
        ("Ultrassonografia Abdominal", "Imagem por ultrassom dos órgãos abdominais"),
        ("Teste de Gravidez (Beta-hCG)", "Detecção da presença do hormônio beta-hCG"),
        ("Creatinina", "	Avaliação da função renal"),
        ("TGO e TGP", "Marcadores hepáticos"),
        ("Teste de Tolerância à Glicose", "Avaliação da resposta do corpo à glicose"),
        ("Teste de Função Pulmonar", "Medição da capacidade pulmonar"),
        ("Dosagem de Vitamina D", "Avaliação dos níveis de vitamina D no sangue"),
        (
            "Hemoglobina Glicada (A1c)",
            "Controle dos níveis médios de glicose no sangue",
        ),
        ("Dosagem de Ferro", "	Avaliação dos níveis de ferro no sangue"),
        ("Teste de Coagulação", "Avaliação da coagulação sanguínea"),
        (
            "Tomografia Computadorizada (TC)",
            "Imagem tridimensional de áreas específicas",
        ),
        ("Ressonância Magnética (RM)", "	Imagem detalhada de tecidos e órgãos"),
        ("Urografia Excretora", "Avaliação do sistema urinário"),
        ("PSA (Antígeno Prostático Específico)",
         "Rastreamento do câncer de próstata"),
        ("Colonoscopia", "Exame do intestino grosso"),
        ("Eletroencefalograma (EEG)", "	Registro da atividade elétrica cerebral"),
        ("Teste de Função Hepática", "Avaliação da função do fígado"),
        ("Cultura de Urina", "Identificação de microorganismos na urina"),
        ("Teste de HIV", "Detecção do vírus da imunodeficiência humana"),
        ("Mamografia", "Imagem radiográfica das mamas"),
        ("Exame de Papanicolau", "Rastreamento de células cervicais anormais"),
        ("Teste de Tireoide", "	Avaliação dos hormônios tireoidianos"),
        ("Doppler Vascular", "	Avaliação do fluxo sanguíneo"),
        ("Gasometria Arterial", "Análise dos gases no sangue arterial"),
        ("Eletromiografia (EMG)", "Avaliação da atividade elétrica dos músculos"),
        ("Exame de Urina", "Avaliação física e química da urina"),
        ("Holter 24 Horas", "	Monitoramento contínuo da atividade cardíaca"),
        ("Dosagem de Sódio e Potássio", "Avaliação dos eletrólitos no sangue"),
        ("Ecocardiograma", "Imagem ultrassonográfica do coração"),
        ("Teste de alergia", "Identificação de reações alérgicas"),
        ("Sorologia para Dengue", "Detecção de anticorpos contra o vírus da dengue"),
        ("Dosagem de TSH", "Avaliação do hormônio estimulante da tireoide"),
        ("Cultura de Sangue", "Identificação de microorganismos no sangue"),
        ("Teste de Função Renal", "Avaliação global da função renal"),
        ("Teste de Paternidade", "Determinação da relação genética entre pessoas"),
        ("Eletroneuromiografia (ENMG)", "Avaliação da atividade elétrica nervosa"),
        ("PCR (Proteína C-Reativa)", "Avaliação de processos inflamatórios"),
        (
            "Teste Ergométrico (Esteira)",
            "Avaliação da função cardíaca durante o exercício",
        ),
        (
            "Avaliação de Composição Corporal",
            "Medição da quantidade de massa magra e massa gorda no corpo.",
        ),
        (
            "Avaliação de Flexibilidade",
            "Medição da amplitude de movimento nas articulações.",
        ),
        (
            "Teste de Resistência Muscular",
            "Avaliação da capacidade dos músculos de realizar trabalho repetido ao longo do tempo.",
        ),
        (
            "Teste de Equilíbrio Dinâmico",
            "Avaliação da capacidade de manter o equilíbrio durante movimentos.",
        ),
        (
            "Índice de Massa Corporal (IMC)",
            "Cálculo baseado na altura e no peso, usado para avaliar a adequação do peso corporal.",
        ),
        (
            "Avaliação da Frequência Cardíaca em Repouso",
            "Medição da frequência cardíaca quando o corpo está em repouso.",
        ),
        (
            "Teste de Potência Muscular",
            "Avaliação da taxa na qual o trabalho é realizado.",
        ),
        (
            "Teste de Agilidade",
            "Avaliação da capacidade de realizar movimentos rápidos e eficientes.",
        ),
        (
            "Avaliação de Postura",
            "Análise da posição do corpo em repouso e durante o movimento.",
        ),
        (
            "Teste de Resistência Cardiovascular",
            "Avaliação da capacidade do sistema cardiovascular de fornecer oxigênio aos músculos durante o exercício.",
        ),
        (
            "Avaliação de Níveis de Estresse",
            "Monitoramento dos níveis de estresse por meio de indicadores fisiológicos.",
        ),
        (
            "Avaliação da Densidade Óssea",
            "Medição da densidade mineral óssea para avaliar a saúde dos ossos.",
        ),
        (
            "Teste de Coordenação Motora",
            "Avaliação da capacidade de coordenar movimentos.",
        ),
        ("Teste de Sprints", "Avaliação da velocidade em corridas curtas."),
        ("Avaliação de Pressão Arterial",
         "Medição da pressão do sangue nas artérias."),
        (
            "Teste de Flexão e Extensão de Braços",
            "Avaliação da força nos músculos dos braços.",
        ),
        (
            "Teste de Resistência Anaeróbica",
            "Avaliação da capacidade de resistir à fadiga durante atividades de alta intensidade.",
        ),
        (
            "Avaliação da Mobilidade Articular",
            "Medição da amplitude de movimento nas articulações.",
        ),
        (
            "Teste de Estabilidade do Core",
            "Avaliação da força e estabilidade dos músculos do core.",
        ),
        (
            "Avaliação da Capacidade Pulmonar",
            "Medição da quantidade máxima de ar que pode ser inspirada e expirada.",
        ),
    ]


def specialty_data_populate():
    return [
        "Clínica Geral",
        "Pediatria",
        "Ginecologia e Obstetrícia",
        "Ortopedia",
        "Cardiologia",
        "Dermatologia",
        "Oftalmologia",
        "Otorrinolaringologia",
        "Neurologia",
        "Psiquiatria",
        "Endocrinologia",
        "Gastroenterologia",
        "Urologia",
        "Radiologia",
        "Medicina do Esporte",
        "Ortopedia Esportiva",
        "Fisioterapia Esportiva",
        "Medicina Física e Reabilitação",
        "Nutrologia Esportiva",
        "Cirurgia do Joelho e Ombro",
    ]
